// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateProduct.sql

package database

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :execresult
INSERT INTO products (
    api_id,
    type_id,
    release_date,
    title,
    artist_id,
    price,
    cover
)
VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateProductParams struct {
	ApiID       string         `json:"api_id"`
	TypeID      int32          `json:"type_id"`
	ReleaseDate sql.NullTime   `json:"release_date"`
	Title       string         `json:"title"`
	ArtistID    int32          `json:"artist_id"`
	Price       int32          `json:"price"`
	Cover       sql.NullString `json:"cover"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProduct,
		arg.ApiID,
		arg.TypeID,
		arg.ReleaseDate,
		arg.Title,
		arg.ArtistID,
		arg.Price,
		arg.Cover,
	)
}
