// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateInventoryItem.sql

package database

import (
	"context"
	"database/sql"
)

const createInventoryItem = `-- name: CreateInventoryItem :execresult
INSERT INTO inventory (
    product_id,
    stock
) VALUES (
    ?,
    ?
)
`

type CreateInventoryItemParams struct {
	ProductID int32 `json:"product_id"`
	Stock     int32 `json:"stock"`
}

func (q *Queries) CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createInventoryItem, arg.ProductID, arg.Stock)
}
