// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateProductType.sql

package database

import (
	"context"
	"database/sql"
)

const createProductType = `-- name: CreateProductType :execresult
INSERT INTO product_types (type_name)
VALUES (?)
`

func (q *Queries) CreateProductType(ctx context.Context, typeName string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createProductType, typeName)
}
