// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateInventoryItemByAPIID.sql

package database

import (
	"context"
	"database/sql"
)

const createInventoryItemByAPIID = `-- name: CreateInventoryItemByAPIID :execresult
INSERT INTO inventory (product_id, stock)
SELECT id, ?
FROM products
WHERE api_id = ?
  AND deleted_at IS NULL
`

type CreateInventoryItemByAPIIDParams struct {
	Stock int32  `json:"stock"`
	ApiID string `json:"api_id"`
}

func (q *Queries) CreateInventoryItemByAPIID(ctx context.Context, arg CreateInventoryItemByAPIIDParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createInventoryItemByAPIID, arg.Stock, arg.ApiID)
}
