// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateSaleItem.sql

package database

import (
	"context"
	"database/sql"
)

const createSaleItem = `-- name: CreateSaleItem :execresult
INSERT INTO sale_item (sale_id, product_id, product_amount)
VALUES (
    ?,
    ?,
    ?
)
`

type CreateSaleItemParams struct {
	SaleID        int32 `json:"sale_id"`
	ProductID     int32 `json:"product_id"`
	ProductAmount int32 `json:"product_amount"`
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSaleItem, arg.SaleID, arg.ProductID, arg.ProductAmount)
}
