// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateInventoryLog.sql

package database

import (
	"context"
	"database/sql"
)

const createInventoryLog = `-- name: CreateInventoryLog :execresult
INSERT INTO inventory_log (product_id, amount, type_id)
VALUES (
    ?,
    ?,
    (SELECT id FROM inventory_log_type WHERE type_name = ? AND deleted_at IS NULL)
)
`

type CreateInventoryLogParams struct {
	ProductID int32  `json:"product_id"`
	Amount    int32  `json:"amount"`
	TypeName  string `json:"type_name"`
}

func (q *Queries) CreateInventoryLog(ctx context.Context, arg CreateInventoryLogParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createInventoryLog, arg.ProductID, arg.Amount, arg.TypeName)
}
