// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateArtist.sql

package database

import (
	"context"
	"database/sql"
)

const createArtist = `-- name: CreateArtist :execresult
INSERT INTO artists (
    name,
    api_id
)
VALUES (
    ?,
    ?
)
`

type CreateArtistParams struct {
	Name  string `json:"name"`
	ApiID string `json:"api_id"`
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createArtist, arg.Name, arg.ApiID)
}
