// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: CreateSale.sql

package database

import (
	"context"
	"database/sql"
)

const createSale = `-- name: CreateSale :execresult
INSERT INTO sales (date_time)
VALUES (CURRENT_TIMESTAMP)
`

func (q *Queries) CreateSale(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSale)
}
