// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetAllSales.sql

package database

import (
	"context"
)

const getAllSales = `-- name: GetAllSales :many
SELECT id, date_time, deleted_at FROM sales
WHERE deleted_at IS NULL
ORDER BY date_time DESC
`

func (q *Queries) GetAllSales(ctx context.Context) ([]Sale, error) {
	rows, err := q.db.QueryContext(ctx, getAllSales)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sale
	for rows.Next() {
		var i Sale
		if err := rows.Scan(&i.ID, &i.DateTime, &i.DeletedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
