// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetAllProducts.sql

package database

import (
	"context"
	"database/sql"
)

const getAllProducts = `-- name: GetAllProducts :many
SELECT
    p.id, p.api_id, p.type_id, p.release_date, p.title, p.artist_id, p.price, p.cover, p.deleted_at,
    COALESCE(i.stock, 0) AS stock
FROM products p
LEFT JOIN inventory i ON p.id = i.product_id AND i.deleted_at IS NULL
WHERE p.deleted_at IS NULL
ORDER BY p.id
`

type GetAllProductsRow struct {
	ID          int32          `json:"id"`
	ApiID       string         `json:"api_id"`
	TypeID      int32          `json:"type_id"`
	ReleaseDate sql.NullTime   `json:"release_date"`
	Title       string         `json:"title"`
	ArtistID    int32          `json:"artist_id"`
	Price       int32          `json:"price"`
	Cover       sql.NullString `json:"cover"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	Stock       int32          `json:"stock"`
}

func (q *Queries) GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllProductsRow
	for rows.Next() {
		var i GetAllProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiID,
			&i.TypeID,
			&i.ReleaseDate,
			&i.Title,
			&i.ArtistID,
			&i.Price,
			&i.Cover,
			&i.DeletedAt,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
