// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetArtistByAPIID.sql

package database

import (
	"context"
)

const getArtistByAPIID = `-- name: GetArtistByAPIID :one
SELECT id, api_id, name, deleted_at FROM artists
WHERE api_id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetArtistByAPIID(ctx context.Context, apiID string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByAPIID, apiID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.ApiID,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}
