// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetArtistByName.sql

package database

import (
	"context"
)

const getArtistByName = `-- name: GetArtistByName :one
SELECT id, api_id, name, deleted_at FROM artists
WHERE name = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetArtistByName(ctx context.Context, artistName string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByName, artistName)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.ApiID,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}
