// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetArtistByID.sql

package database

import (
	"context"
)

const getArtistByID = `-- name: GetArtistByID :one
SELECT id, api_id, name, deleted_at FROM artists
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetArtistByID(ctx context.Context, artistID int32) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistByID, artistID)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.ApiID,
		&i.Name,
		&i.DeletedAt,
	)
	return i, err
}
