// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetInventoryProductByID.sql

package database

import (
	"context"
)

const getInventoryByProductID = `-- name: GetInventoryByProductID :one
SELECT id, product_id, stock, deleted_at FROM inventory
WHERE product_id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetInventoryByProductID(ctx context.Context, productID int32) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryByProductID, productID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Stock,
		&i.DeletedAt,
	)
	return i, err
}
