// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetInventoryProductByAPIID.sql

package database

import (
	"context"
)

const getInventoryProductByAPIID = `-- name: GetInventoryProductByAPIID :one
SELECT i.id, i.product_id, i.stock, i.deleted_at
FROM inventory i
JOIN products p ON i.product_id = p.id
WHERE p.api_id = ?
  AND i.deleted_at IS NULL
  AND p.deleted_at IS NULL
`

func (q *Queries) GetInventoryProductByAPIID(ctx context.Context, apiID string) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventoryProductByAPIID, apiID)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Stock,
		&i.DeletedAt,
	)
	return i, err
}
