// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetProductTypeByID.sql

package database

import (
	"context"
)

const getProductTypeByID = `-- name: GetProductTypeByID :one
SELECT id, type_name, deleted_at FROM product_types
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetProductTypeByID(ctx context.Context, typeID int32) (ProductType, error) {
	row := q.db.QueryRowContext(ctx, getProductTypeByID, typeID)
	var i ProductType
	err := row.Scan(&i.ID, &i.TypeName, &i.DeletedAt)
	return i, err
}
