// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetProductTypeByTypeName.sql

package database

import (
	"context"
)

const getProductTypeByTypeName = `-- name: GetProductTypeByTypeName :one
SELECT id, type_name, deleted_at FROM product_types
WHERE type_name = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetProductTypeByTypeName(ctx context.Context, typeName string) (ProductType, error) {
	row := q.db.QueryRowContext(ctx, getProductTypeByTypeName, typeName)
	var i ProductType
	err := row.Scan(&i.ID, &i.TypeName, &i.DeletedAt)
	return i, err
}
