// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetProductListPage.sql

package database

import (
	"context"
	"database/sql"
)

const getProductsListPage = `-- name: GetProductsListPage :many
SELECT
    p.id,
    p.api_id,
    p.type_id,
    pt.type_name,
    p.release_date,
    p.title,
    p.artist_id,
    a.name AS artist_name,
    p.price,
    p.cover,
    COALESCE(i.stock, 0) AS stock
FROM products p
JOIN artists a ON p.artist_id = a.id
JOIN product_types pt ON p.type_id = pt.id
LEFT JOIN inventory i ON p.id = i.product_id AND i.deleted_at IS NULL
WHERE p.deleted_at IS NULL
  AND a.deleted_at IS NULL
  AND pt.deleted_at IS NULL
LIMIT ?
OFFSET ?
`

type GetProductsListPageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetProductsListPageRow struct {
	ID          int32          `json:"id"`
	ApiID       string         `json:"api_id"`
	TypeID      int32          `json:"type_id"`
	TypeName    string         `json:"type_name"`
	ReleaseDate sql.NullTime   `json:"release_date"`
	Title       string         `json:"title"`
	ArtistID    int32          `json:"artist_id"`
	ArtistName  string         `json:"artist_name"`
	Price       int32          `json:"price"`
	Cover       sql.NullString `json:"cover"`
	Stock       int32          `json:"stock"`
}

func (q *Queries) GetProductsListPage(ctx context.Context, arg GetProductsListPageParams) ([]GetProductsListPageRow, error) {
	rows, err := q.db.QueryContext(ctx, getProductsListPage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsListPageRow
	for rows.Next() {
		var i GetProductsListPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ApiID,
			&i.TypeID,
			&i.TypeName,
			&i.ReleaseDate,
			&i.Title,
			&i.ArtistID,
			&i.ArtistName,
			&i.Price,
			&i.Cover,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
