// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetProductByID.sql

package database

import (
	"context"
	"database/sql"
)

const getProductByID = `-- name: GetProductByID :one
SELECT
    p.id, p.api_id, p.type_id, p.release_date, p.title, p.artist_id, p.price, p.cover, p.deleted_at,
    COALESCE(i.stock, 0) AS stock
FROM products p
LEFT JOIN inventory i ON p.id = i.product_id AND i.deleted_at IS NULL
WHERE p.id = ?
  AND p.deleted_at IS NULL
`

type GetProductByIDRow struct {
	ID          int32          `json:"id"`
	ApiID       string         `json:"api_id"`
	TypeID      int32          `json:"type_id"`
	ReleaseDate sql.NullTime   `json:"release_date"`
	Title       string         `json:"title"`
	ArtistID    int32          `json:"artist_id"`
	Price       int32          `json:"price"`
	Cover       sql.NullString `json:"cover"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
	Stock       int32          `json:"stock"`
}

func (q *Queries) GetProductByID(ctx context.Context, productID int32) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, productID)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.ApiID,
		&i.TypeID,
		&i.ReleaseDate,
		&i.Title,
		&i.ArtistID,
		&i.Price,
		&i.Cover,
		&i.DeletedAt,
		&i.Stock,
	)
	return i, err
}
