// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetSaleByID.sql

package database

import (
	"context"
)

const getSaleByID = `-- name: GetSaleByID :one
SELECT id, date_time, deleted_at FROM sales
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetSaleByID(ctx context.Context, saleID int32) (Sale, error) {
	row := q.db.QueryRowContext(ctx, getSaleByID, saleID)
	var i Sale
	err := row.Scan(&i.ID, &i.DateTime, &i.DeletedAt)
	return i, err
}
