// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetSaleItemBySaleID.sql

package database

import (
	"context"
	"database/sql"
)

const getSaleItemsBySaleID = `-- name: GetSaleItemsBySaleID :many
SELECT
    si.id          AS sale_item_id,
    si.product_id,
    si.product_amount,
    p.api_id       AS product_api_id,
    p.title        AS product_title,
    p.price        AS product_price,
    p.cover        AS product_cover,
    a.name         AS artist_name,
    a.id           AS artist_id,
    pt.type_name   AS product_type,
    pt.id          AS type_id,
    COALESCE(inv.stock, 0) AS stock
FROM sale_item si
JOIN products p ON si.product_id = p.id AND p.deleted_at IS NULL
JOIN artists a ON p.artist_id = a.id AND a.deleted_at IS NULL
JOIN product_types pt ON p.type_id = pt.id AND pt.deleted_at IS NULL
LEFT JOIN inventory inv ON p.id = inv.product_id AND inv.deleted_at IS NULL
WHERE si.sale_id = ?
  AND si.deleted_at IS NULL
`

type GetSaleItemsBySaleIDRow struct {
	SaleItemID    int32          `json:"sale_item_id"`
	ProductID     int32          `json:"product_id"`
	ProductAmount int32          `json:"product_amount"`
	ProductApiID  string         `json:"product_api_id"`
	ProductTitle  string         `json:"product_title"`
	ProductPrice  int32          `json:"product_price"`
	ProductCover  sql.NullString `json:"product_cover"`
	ArtistName    string         `json:"artist_name"`
	ArtistID      int32          `json:"artist_id"`
	ProductType   string         `json:"product_type"`
	TypeID        int32          `json:"type_id"`
	Stock         int32          `json:"stock"`
}

func (q *Queries) GetSaleItemsBySaleID(ctx context.Context, saleID int32) ([]GetSaleItemsBySaleIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getSaleItemsBySaleID, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSaleItemsBySaleIDRow
	for rows.Next() {
		var i GetSaleItemsBySaleIDRow
		if err := rows.Scan(
			&i.SaleItemID,
			&i.ProductID,
			&i.ProductAmount,
			&i.ProductApiID,
			&i.ProductTitle,
			&i.ProductPrice,
			&i.ProductCover,
			&i.ArtistName,
			&i.ArtistID,
			&i.ProductType,
			&i.TypeID,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
