// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: GetUserByID.sql

package database

import (
	"context"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, deleted_at FROM users
WHERE id = ?
  AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, userID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DeletedAt,
	)
	return i, err
}
