// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Artist struct {
	ID        int32        `json:"id"`
	ApiID     string       `json:"api_id"`
	Name      string       `json:"name"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Inventory struct {
	ID        int32        `json:"id"`
	ProductID int32        `json:"product_id"`
	Stock     int32        `json:"stock"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type InventoryLog struct {
	ID        int32        `json:"id"`
	DateTime  sql.NullTime `json:"date_time"`
	ProductID int32        `json:"product_id"`
	Amount    int32        `json:"amount"`
	TypeID    int32        `json:"type_id"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type InventoryLogType struct {
	ID        int32        `json:"id"`
	TypeName  string       `json:"type_name"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Product struct {
	ID          int32          `json:"id"`
	ApiID       string         `json:"api_id"`
	TypeID      int32          `json:"type_id"`
	ReleaseDate sql.NullTime   `json:"release_date"`
	Title       string         `json:"title"`
	ArtistID    int32          `json:"artist_id"`
	Price       int32          `json:"price"`
	Cover       sql.NullString `json:"cover"`
	DeletedAt   sql.NullTime   `json:"deleted_at"`
}

type ProductType struct {
	ID        int32        `json:"id"`
	TypeName  string       `json:"type_name"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Sale struct {
	ID        int32        `json:"id"`
	DateTime  sql.NullTime `json:"date_time"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type SaleItem struct {
	ID            int32        `json:"id"`
	SaleID        int32        `json:"sale_id"`
	ProductID     int32        `json:"product_id"`
	ProductAmount int32        `json:"product_amount"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
}

type User struct {
	ID           int32        `json:"id"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
}
