// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateArtist(ctx context.Context, arg CreateArtistParams) (sql.Result, error)
	CreateInventoryItem(ctx context.Context, arg CreateInventoryItemParams) (sql.Result, error)
	CreateInventoryItemByAPIID(ctx context.Context, arg CreateInventoryItemByAPIIDParams) (sql.Result, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetAllProducts(ctx context.Context) ([]GetAllProductsRow, error)
	GetArtistByID(ctx context.Context, artistID int32) (Artist, error)
	GetArtistByName(ctx context.Context, artistName string) (Artist, error)
	GetInventoryByProductID(ctx context.Context, productID int32) (Inventory, error)
	GetProductByID(ctx context.Context, productID int32) (GetProductByIDRow, error)
	GetProductTypeByID(ctx context.Context, typeID int32) (ProductType, error)
	GetProductTypeByTypeName(ctx context.Context, typeName string) (ProductType, error)
	GetProductsListPage(ctx context.Context, arg GetProductsListPageParams) ([]GetProductsListPageRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, userID int32) (User, error)
}

var _ Querier = (*Queries)(nil)
