// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: SetInventoryStock.sql

package database

import (
	"context"
	"database/sql"
)

const setInventoryStock = `-- name: SetInventoryStock :execresult
UPDATE inventory
SET stock = ?
WHERE product_id = ?
  AND deleted_at IS NULL
`

type SetInventoryStockParams struct {
	NewStock  int32 `json:"new_stock"`
	ProductID int32 `json:"product_id"`
}

func (q *Queries) SetInventoryStock(ctx context.Context, arg SetInventoryStockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setInventoryStock, arg.NewStock, arg.ProductID)
}
