// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: UpdateProduct.sql

package database

import (
	"context"
	"database/sql"
)

const updateProduct = `-- name: UpdateProduct :execresult
UPDATE products
SET
    api_id       = ?,
    type_id      = ?,
    release_date = ?,
    title        = ?,
    artist_id    = ?,
    price        = ?,
    cover        = ?
WHERE id = ?
`

type UpdateProductParams struct {
	ApiID       string         `json:"api_id"`
	TypeID      int32          `json:"type_id"`
	ReleaseDate sql.NullTime   `json:"release_date"`
	Title       string         `json:"title"`
	ArtistID    int32          `json:"artist_id"`
	Price       int32          `json:"price"`
	Cover       sql.NullString `json:"cover"`
	ProductID   int32          `json:"product_id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateProduct,
		arg.ApiID,
		arg.TypeID,
		arg.ReleaseDate,
		arg.Title,
		arg.ArtistID,
		arg.Price,
		arg.Cover,
		arg.ProductID,
	)
}
