// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: UpdateInventoryStock.sql

package database

import (
	"context"
	"database/sql"
)

const updateInventoryStock = `-- name: UpdateInventoryStock :execresult
UPDATE inventory
SET stock = stock - ?
WHERE product_id = ?
  AND stock >= ?
  AND deleted_at IS NULL
`

type UpdateInventoryStockParams struct {
	Amount    int32 `json:"amount"`
	ProductID int32 `json:"product_id"`
}

func (q *Queries) UpdateInventoryStock(ctx context.Context, arg UpdateInventoryStockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateInventoryStock, arg.Amount, arg.ProductID, arg.Amount)
}
